# Generated by Django 3.2.2 on 2021-06-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='vaqt',
            field=models.DateTimeField(null=True),
        ),
    ]
