# Generated by Django 3.2.4 on 2021-06-25 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_article_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='vaqt',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
