# Generated by Django 3.2.2 on 2021-06-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=60, verbose_name='Kategoriya nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=80, verbose_name='Nomi')),
                ('muallif', models.CharField(max_length=50, verbose_name='Muallif:')),
                ('tarif', models.TextField(null=True)),
                ('rasm', models.ImageField(null=True, upload_to='')),
                ('toifa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.category')),
            ],
        ),
    ]
